const ARTICLES = [
    {
        title: "",
        thumbnail: "/design/فضل_الصلاة_على_النبي/images/thumbnail.jpg",
        thumbnailALT: "فضل الصلاة على النبي",
        url: "/design/فضل_الصلاة_على_النبي/",
        tags: ["سنن نبوية"],
    }, {
        title: "",
        thumbnail: "/design/rainAndWindSunnah/images/thumbnail.jpg",
        url: "/design/rainAndWindSunnah/",
        thumbnailALT: "سنن المطر والريح",
        tags: ["سنن نبوية"]
    },
];

const POSTS = [
    {
        title: "",
        dirPath: "/design/images/002/",
        thumbnail: "6.jpg",
        thumbnailALT: "إنّا لله وإنّا إليهِ رَاجعُون",
        images: [
            "6.jpg",
            "1.jpg",
            "2.jpg",
            "3.jpg",
            "4.jpg",
            "5.jpg",
            "7.jpg",
            "8.jpg",
            "9.jpg",
            "10.jpg",
        ],
        imageHighQualityURL: "https://drive.google.com/drive/folders/1op6Pf2CBM7JdvXptS49DWZDtSPkSI_J9?usp=sharing",
        tags: ["آيات قرآنية"]
    }, {
        title: "",
        dirPath: "/design/images/001/",
        thumbnail: "1.jpg",
        thumbnailALT: "أَفَلا يَتُوبُونَ إِلَى اللَّهِ وَيَسْتَغْفِرُونَهُ وَاللَّهُ غَفُورٌ رَحِيمٌ",
        images: [
            "1.jpg",
            "2.jpg",
            "3.jpg",
            "4.jpg",
            "5.jpg",
        ],
        imageHighQualityURL: "https://drive.google.com/drive/folders/1ZvM-J5tKCXx7oSm0N1JLbkha4pu3Fd1J?usp=sharing",
        tags: ["آيات قرآنية"]
    }, {
        title: "",
        dirPath: "/design/images/003/",
        thumbnail: "9.jpg",
        thumbnailALT: "إِنَّمَا يُوَفَّى الصَّابِرُونَ أَجْرَهُمْ بِغَيْرِ حِسَابٍ",
        images: [
            "9.jpg",
            "1.jpg",
            "2.jpg",
            "3.jpg",
            "4.jpg",
            "5.jpg",
            "6.jpg",
            "7.jpg",
            "8.jpg",
            "10.jpg",
            "11.jpg",
            "12.jpg",
            "13.jpg",
        ],
        imageHighQualityURL: "https://drive.google.com/drive/folders/1XuYFi50XuXMY8pSFatA2oB8l3bPR5mdi?usp=sharing",
        tags: ["آيات قرآنية"]
    }, {
        title: "",
        dirPath: "/design/images/004/",
        thumbnail: "1.jpg",
        thumbnailALT: "هُنَالِكَ دَعَا زَكَرِيَّا رَبَّهُ ۖ قَالَ رَبِّ هَبْ لِي مِن لَّدُنكَ ذُرِّيَّةً طَيِّبَةً ۖ إِنَّكَ سَمِيعُ الدُّعَاءِ (آل عمران - 38)",
        images: [
            "1.jpg",
            "2.jpg",
            "3.jpg",
            "4.jpg",
            "5.jpg",
            "6.jpg",
            "7.jpg",
            "8.jpg",
            "9.jpg",
            "10.jpg",
            "11.jpg",
            "12.jpg",
            "13.jpg",
        ],
        imageHighQualityURL: "https://drive.google.com/drive/folders/1VPSFUaWdv1YQOCB82RyNt5zjf5XdZmci?usp=sharing",
        tags: ["آيات قرآنية"]
    }, {
        title: "",
        dirPath: "/design/images/005/",
        thumbnail: "1.jpg",
        thumbnailALT: "لَّا إِلَٰهَ إِلَّا أَنتَ سُبْحَانَكَ إِنِّي كُنتُ مِنَ الظَّالِمِينَ",
        images: [
            "1.jpg",
            "2.jpg",
            "3.jpg",
            "4.jpg",
            "5.jpg",
            "6.jpg",
            "7.jpg",
            "8.jpg",
            "9.jpg",
            "10.jpg",
        ],
        imageHighQualityURL: "https://drive.google.com/drive/folders/1kO03Hwa2W_TSfYIGnQKruruiWcW2Uci7?usp=sharing",
        tags: ["آيات قرآنية"]
    }, {
        title: "",
        dirPath: "/design/images/006/",
        thumbnail: "1.jpg",
        thumbnailALT: "وَلِلَّهِ مُلْكُ السَّمَاوَاتِ وَالْأَرْضِ ۗ وَاللَّهُ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ (آل عمران - 189)",
        images: [
            "1.jpg",
            "2.jpg",
            "3.jpg",
            "4.jpg",
            "5.jpg",
            "6.jpg",
            "7.jpg",
            "8.jpg",
            "9.jpg",
            "10.jpg",
            "11.jpg",
        ],
        imageHighQualityURL: "https://drive.google.com/drive/folders/12sXs8GnYkJy3tiOL-JxFS6-swn6nw3K5?usp=sharing",
        tags: ["آيات قرآنية"]
    }, {
        title: "",
        dirPath: "/design/images/007/",
        thumbnail: "4.jpg",
        thumbnailALT: "وَقَالُواْ ٱلۡحَمۡدُ لِلَّهِ ٱلَّذِيٓ أَذۡهَبَ عَنَّا ٱلۡحَزَنَۖ إِنَّ رَبَّنَا لَغَفُورٞ شَكُورٌ",
        images: [
            "4.jpg",
            "1.jpg",
            "2.jpg",
            "3.jpg",
            "5.jpg",
        ],
        imageHighQualityURL: "https://drive.google.com/drive/folders/1KSemYDunabB3UGtRceYPbJgd2UL1flwb?usp=sharing",
        tags: ["آيات قرآنية"]
    }, {
        title: "",
        dirPath: "/design/images/008/",
        thumbnail: "1.jpg",
        thumbnailALT: "وَلَمَّا أَن جَاءَتْ رُسُلُنَا لُوطًا سِيءَ بِهِمْ وَضَاقَ بِهِمْ ذَرْعًا وَقَالُوا لَا تَخَفْ وَلَا تَحْزَنْ ۖ إِنَّا مُنَجُّوكَ وَأَهْلَكَ إِلَّا امْرَأَتَكَ كَانَتْ مِنَ الْغَابِرِينَ (العنكبوت - 33)",
        images: [
            "1.jpg",
            "2.jpg",
            "3.jpg",
            "4.jpg",
            "5.jpg",
            "6.jpg",
            "7.jpg",
            "8.jpg",
            "9.jpg",
            "10.jpg",
            "11.jpg",
            "12.jpg",
        ],
        imageHighQualityURL: "https://drive.google.com/drive/folders/1YrImbpNLFR2_mUJKRe8OMj8pU_u_h0iJ?usp=sharing",
        tags: ["آيات قرآنية"]
    }, {
        title: "",
        dirPath: "/design/images/009/",
        thumbnail: "1.jpg",
        thumbnailALT: "وَلْيَخْشَ الَّذِينَ لَوْ تَرَكُوا مِنْ خَلْفِهِمْ ذُرِّيَّةً ضِعَافًا خَافُوا عَلَيْهِمْ فَلْيَتَّقُوا اللَّهَ وَلْيَقُولُوا قَوْلًا سَدِيدًا",
        images: [
            "1.jpg",
            "2.jpg",
            "3.jpg",
            "4.jpg",
        ],
        imageHighQualityURL: "",
        tags: ["آيات قرآنية"]
    }, {
        title: "",
        dirPath: "/design/images/010/",
        thumbnail: "1.jpg",
        thumbnailALT: "وَمَا لَنَا أَلَّا نَتَوَكَّلَ عَلَى اللَّهِ وَقَدْ هَدَانَا سُبُلَنَا",
        images: [
            "1.jpg",
            "2.jpg",
            "3.jpg",
            "4.jpg",
            "5.jpg",
        ],
        imageHighQualityURL: "https://drive.google.com/drive/folders/1DypHLz3pp8OpEMs9y5to2pSRwlJngu47?usp=sharing",
        tags: ["آيات قرآنية"]
    }, {
        title: "",
        dirPath: "/design/images/011/",
        thumbnail: "1.jpg",
        thumbnailALT: "وَمَنْ يَعْمَلْ سُوءًا أَوْ يَظْلِمْ نَفْسَهُ ثُمَّ يَسْتَغْفِرِ اللَّهَ يَجِدِ اللَّهَ غَفُورًا رَحِيمًا",
        images: [
            "1.jpg",
            "2.jpg",
            "3.jpg",
            "4.jpg",
            "5.jpg",
            "6.jpg",
            "7.jpg",
            "8.jpg",
        ],
        imageHighQualityURL: "https://drive.google.com/drive/folders/1YT9gU3PQBtrYVeGb0csFuLkRnpCFEteN?usp=sharing",
        tags: ["آيات قرآنية"]
    }, {
        title: "",
        dirPath: "/design/images/012/",
        thumbnail: "13.jpg",
        thumbnailALT: "يَا حَيُّ يَا قَــيُّومُ بِرَحْمَتِكَ أَسْتَغِيثُ، أَصْلِحْ لِي شَأْنِي كُلَّهُ، وَلَا تَكِلْنِي إِلَى نَفْسِي طَرْفَةَ عَيْنٍ",
        images: [
            "13.jpg",
            "1.jpg",
            "2.jpg",
            "3.jpg",
            "4.jpg",
            "5.jpg",
            "6.jpg",
            "7.jpg",
            "8.jpg",
            "9.jpg",
            "10.jpg",
            "11.jpg",
            "12.jpg",
            "14.jpg",
        ],
        imageHighQualityURL: "https://drive.google.com/drive/folders/1bXussR1vxE4Q8CbsZf2_TEoRq7RC7GfN?usp=sharing",
        tags: ["أحاديث نبوية"]
    }, {
        title: "",
        dirPath: "/design/images/014/",
        thumbnail: "1.jpg",
        thumbnailALT: "إنَّ الأعمالَ تُعرَضُ يومَ الاثنينِ والخميسِ",
        images: [
            "1.jpg",
            "2.jpg",
        ],
        imageHighQualityURL: "https://drive.google.com/drive/folders/1s8XPi1f2L5F_YXARo1iedA4zwdTkyzcH?usp=sharing",
        tags: ["أحاديث نبوية"]
    }, {
        title: "",
        dirPath: "/design/images/015/",
        thumbnail: "1.jpg",
        thumbnailALT: "مَن أصبحَ منكم آمنًا في سربِهِ ، مُعافًى في جسدِهِ عندَهُ قوتُ يومِهِ ، فَكَأنَّما حيزت لَهُ الدُّنيا",
        images: [
            "1.jpg",
            "2.jpg",
            "3.jpg",
            "4.jpg",
            "5.jpg",
        ],
        imageHighQualityURL: "https://drive.google.com/drive/folders/126-XHJ36gVLtk6BB0D99liSRaBs6EQL-?usp=sharing",
        tags: ["أحاديث نبوية"]
    }, {
        title: "",
        dirPath: "/design/images/016/",
        thumbnail: "1.jpg",
        thumbnailALT: "“ من صدق في طلب الحق وجده “ فريد الأنصاري -رحمه الله",
        images: [
            "1.jpg",
            "2.jpg",
            "3.jpg",
            "4.jpg",
            "5.jpg",
            "6.jpg",
            "7.jpg",
        ],
        imageHighQualityURL: "https://drive.google.com/drive/folders/1_6W-Nj7amG426T-6Co3TlsjU3cGbjNjP?usp=sharing",
        tags: ["مقولات عربية"]
    }, {
        title: "",
        dirPath: "/design/images/017/",
        thumbnail: "1.jpg",
        thumbnailALT: "قال أمير المؤمنين عمر بن الخطّاب رضي الله عنه : من كثُرَ كلامُهُ كثُرَ لغطُهُ، ومن كثُرَ لغطُهُ كثُرَ غلطُهُ، ومن كثُرَ غلطُهُ قلّ ورعُهُ، ومن قلّ ورعُهُ قلّ دينُه.",
        images: [
            "1.jpg",
            "2.jpg",
        ],
        imageHighQualityURL: "https://drive.google.com/drive/folders/1t5YfyAyiiEwDC9Br37PJnZI0gDkDT1tX?usp=sharing",
        tags: ["مقولات عربية"]
    }, {
        title: "",
        dirPath: "/design/images/018/",
        thumbnail: "1.jpg",
        thumbnailALT: "الْمَقْصِدُ الشَّرْعِيُّ مِنْ وَضْعِ الشَّرِيعَةِ إِخْرَاجَ الْمُكَلَّفِ عَنْ دَاعِيَةِ هَوَاهُ، حَتَّى يَكُونَ عَبْدًا لِلَّهِ اخْتِيَارًا، كَمَا هُوَ عَبْدٌ لِلَّهِ اضْطِرَارًا",
        images: [
            "1.jpg",
            "2.jpg",
            "3.jpg",
        ],
        imageHighQualityURL: "https://drive.google.com/drive/folders/1r51264Fh70CxYfiC4a4DIKzxOfz3O4eh?usp=sharing",
        tags: ["مقولات عربية"]
    }, {
        title: "",
        dirPath: "/design/images/025/",
        thumbnail: "10.jpg",
        thumbnailALT: "من قال حين يصبح وحين يمسي: سبحان الله وبحمده",
        images: [
            "10.jpg",
            "1.jpg",
            "2.jpg",
            "3.jpg",
            "4.jpg",
            "5.jpg",
            "6.jpg",
            "7.jpg",
            "8.jpg",
            "9.jpg",
            "11.jpg",
            "12.jpg",
            "13.jpg",
            "14.jpg",
            "15.jpg",
            "16.jpg",
            "17.jpg",
            "18.jpg",
            "19.jpg",
            "20.jpg",
            "21.jpg",
            "22.jpg",
            "23.jpg",
        ],
        imageHighQualityURL: "",
        tags: ["أحاديث نبوية"]
    }, {
        title: "",
        dirPath: "/design/images/026/",
        thumbnail: "4.jpg",
        thumbnailALT: "يَأْتي علَى النَّاسِ زَمانٌ لا يُبالِي المَرْءُ ما أخَذَ منه؛ أمِنَ الحَلالِ أمْ مِنَ الحَرامِ",
        images: [
            "4.jpg",
            "1.jpg",
            "2.jpg",
            "3.jpg",
            "5.jpg",
            "6.jpg",
            "7.jpg",
            "8.jpg",
            "9.jpg",
            "10.jpg",
            "11.jpg",
            "12.jpg",
            "13.jpg",
            "14.jpg",
            "15.jpg",
            "16.jpg",
            "17.jpg",
            "18.jpg",
            "19.jpg",
            "20.jpg",
            "21.jpg",
            "22.jpg",
        ],
        imageHighQualityURL: "",
        tags: ["أحاديث نبوية"]
    }, {
        title: "",
        dirPath: "/design/images/027/",
        thumbnail: "6.jpg",
        thumbnailALT: "مَن صلى العشاءَ في جماعةٍ كأنما قام نصفَ ليلةٍ ، ومَن صلى الصبحَ في جماعةٍ فكأنما صلى الليلَ كلَّه",
        images: [
            "6.jpg",
            "1.jpg",
            "2.jpg",
            "3.jpg",
            "4.jpg",
            "5.jpg",
            "7.jpg",
            "8.jpg",
            "9.jpg",
            "10.jpg",
        ],
        imageHighQualityURL: "https://drive.google.com/drive/folders/10QnuLQklRZar_y2JWJuDCaIoCCe0w9jk?usp=sharing",
        tags: ["أحاديث نبوية"]
    }, {
        title: "",
        dirPath: "/design/images/028/",
        thumbnail: "12.jpg",
        thumbnailALT: "فإذا فرغت فانصب وإلى ربك فارغب",
        images: [
            "12.jpg",
            "1.jpg",
            "2.jpg",
            "3.jpg",
            "4.jpg",
            "5.jpg",
            "6.jpg",
            "7.jpg",
            "8.jpg",
            "9.jpg",
            "10.jpg",
            "11.jpg",
            "13.jpg",
            "14.jpg",
            "15.jpg",
            "16.jpg",
        ],
        imageHighQualityURL: "https://drive.google.com/drive/folders/1fQrNCflxLmpmGSiGExiOBMaDukw8qn64?usp=sharing",
        tags: ["آيات قرآنية"]
    }
];
